---
# Source: osrm/templates/service-bus.yaml
apiVersion: v1
kind: Service
metadata:
  labels:    
    chart: osrm-0.1.0
    release: osrm
    team: ror
    slack: talk-ror
    type: backend
    namespace: dev
    app: osrm-bus
  name: osrm-bus
  namespace: dev
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: osrm-bus
  sessionAffinity: None
  type: ClusterIP

---
# Source: osrm/templates/service-rail.yaml
apiVersion: v1
kind: Service
metadata:
  labels:    
    chart: osrm-0.1.0
    release: osrm
    team: ror
    slack: talk-ror
    type: backend
    namespace: dev
    app: osrm-rail
  name: osrm-rail
  namespace: dev
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: osrm-rail
  sessionAffinity: None
  type: ClusterIP

---
# Source: osrm/templates/service-water.yaml
apiVersion: v1
kind: Service
metadata:
  labels:    
    chart: osrm-0.1.0
    release: osrm
    team: ror
    slack: talk-ror
    type: backend
    namespace: dev
    app: osrm-water
  name: osrm-water
  namespace: dev
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: osrm-water
  sessionAffinity: None
  type: ClusterIP

---
# Source: osrm/templates/deployment-bus.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm
  namespace: dev
  labels:    
    chart: osrm-0.1.0
    release: osrm
    team: ror
    slack: talk-ror
    type: backend
    namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: osrm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:        
        chart: osrm-0.1.0
        release: osrm
        team: ror
        slack: talk-ror
        type: backend
        namespace: dev
        app: osrm-bus
    spec:
      containers:
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: osrm-bus
          image: ${artifact.metadata.image}
          imagePullPolicy: Always
          command:
            - /docker-entrypoint.sh
            - osrm
            - bus
            - https://storage.googleapis.com/marduk/osm/norway-latest.osm.pbf
          env:
            - name: TZ
              value: Europe/Oslo
          resources:
            limits:
              cpu: 1500m
              memory: 3500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /table/v1/driving/10.8116303,59.9096267;10.7502687,59.911096?sources=0
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31


---
# Source: osrm/templates/deployment-rail.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm
  namespace: dev
  labels:    
    chart: osrm-0.1.0
    release: osrm
    team: ror
    slack: talk-ror
    type: backend
    namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: osrm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:        
        chart: osrm-0.1.0
        release: osrm
        team: ror
        slack: talk-ror
        type: backend
        namespace: dev
        app: osrm-rail
    spec:
      containers:
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: osrm-rail
          image: ${artifact.metadata.image}
          imagePullPolicy: Always
          command:
            - /docker-entrypoint.sh
            - osrm
            - rail
            - https://storage.googleapis.com/marduk/osm/norway-latest.osm.pbf
          env:
            - name: TZ
              value: Europe/Oslo
          resources:
            limits:
              cpu: 1500m
              memory: 3500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /table/v1/driving/10.8116303,59.9096267;10.7502687,59.911096?sources=0
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31


---
# Source: osrm/templates/deployment-water.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm
  namespace: dev
  labels:    
    chart: osrm-0.1.0
    release: osrm
    team: ror
    slack: talk-ror
    type: backend
    namespace: dev
    app: osrm-water
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: osrm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:        
        chart: osrm-0.1.0
        release: osrm
        team: ror
        slack: talk-ror
        type: backend
        namespace: dev
    spec:
      containers:
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - name: osrm-water
          image: ${artifact.metadata.image}
          imagePullPolicy: Always
          command:
            - /docker-entrypoint.sh
            - osrm
            - water
            - https://storage.googleapis.com/marduk/osm/norway-latest.osm.pbf
          env:
            - name: TZ
              value: Europe/Oslo
          resources:
            limits:
              cpu: 1500m
              memory: 3500Mi
            requests:
              cpu: 200m
              memory: 500Mi
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /table/v1/driving/10.8116303,59.9096267;10.7502687,59.911096?sources=0
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 31


